const ADMIN_API_URL="/AdminApi"

const LOGIN_ADMIN_URL=  ADMIN_API_URL+"/LoginAdmin"
const ADMIN_CREATE_ACCOUNT_URL=    ADMIN_API_URL+"/CreateAdmin"
const ADMIN_OTP_CHANGE_PASS_URL=    ADMIN_API_URL+"/AdminChangeOTPPass"
const ADMIN_RESET_PASS_URL=   ADMIN_API_URL+"/AdminResetPass"
const CHANGE_WITH_CONFIRM_PASS = ADMIN_API_URL+"/ChangeWithConfirmPass"
const LOGOUT_ADMIN_URL=    ADMIN_API_URL+"/LogoutAdmin"
const VIEW_ADMIN_PROFILE_URL=    ADMIN_API_URL+"/ViewAdmin"
const UPDATE_ADMIN= ADMIN_API_URL+"/UpdateAdmin"


export {
    LOGIN_ADMIN_URL,
ADMIN_OTP_CHANGE_PASS_URL,
ADMIN_CREATE_ACCOUNT_URL,
ADMIN_RESET_PASS_URL,
LOGOUT_ADMIN_URL,
CHANGE_WITH_CONFIRM_PASS,
VIEW_ADMIN_PROFILE_URL,
UPDATE_ADMIN
}